image: docker:27.3.1-alpine3.20
services:
  - docker:dind

stages:
  - build
  - package
  - deploy

maven-build:
  image: maven:3-eclipse-temurin-23-alpine
  stage: build
  script: "mvn clean package"
