image: eclipse-temurin:23-jdk

services:
  - docker:20.10.16-dind

variables:
  DOCKER_DRIVER: overlay2
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode --errors --fail-at-end --show-version"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - .m2/repository
    - target

before_script:
  - echo "MAVEN_CLI_OPTS=$MAVEN_CLI_OPTS"
  - echo "MAVEN_OPTS=$MAVEN_OPTS"
  - docker info

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean compile

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test

deploy:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS deploy
  only:
    - main
