image: docker:27.3.1-alpine3.20
services:
  - docker:dind

stages:
  - test
  - build
  - package
  - deploy


job_name:
  stage: test
  script:
    - curl -fsSL https://app.testcontainers.cloud/bash | bash
    - "mvn clean test"

maven-build:
  image: maven:3-eclipse-temurin-23-alpine
  stage: build
  script: "mvn clean package"
