image: eclipse-temurin:23-jdk

services:
  - docker:20.10.16-dind

variables:
  DOCKER_DRIVER: overlay2
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode --errors --fail-at-end --show-version"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

stages:
  - test
  - build
  - package
  - deploy

cache:
  paths:
    - .m2/repository
    - target

before_script:
  - apt-get update && apt-get install -y curl bash
  - echo "MAVEN_CLI_OPTS=$MAVEN_CLI_OPTS"
  - echo "MAVEN_OPTS=$MAVEN_OPTS"
  - docker info

test_containers:
  stage: test
  script:
    - curl -fsSL https://app.testcontainers.cloud/bash | bash
    - "mvn clean test"
  only:
    - main
    - test-containers

maven-build:
  image: maven:3-eclipse-temurin-23-alpine
  stage: build
  script: "mvn clean package"
  only:
    - test-containers
